#!/usr/bin/env bash

run() {
  local _channel="$1"
  local _pkg="$2"

  nix-env -f http://nixos.org/channels/"$_channel"/nixexprs.tar.xz -i "$_pkg"; 
}

usage() {
    echo -e "nix-venient install-from-channel <channel> <pkg>: Install package from specific channel\n"
    echo -e "Examples:\n"
    echo -e "  $ nix-venient install-from-channel nixpkgs-unstable hello"
    echo -e "  $ nix-venient install-from-channel nixos-unstable nodejs"
}

if [[ $# -ne 2 || $1 = "--help" ]]; then
    usage
    exit 1
else
    run $*
fi
