#!/usr/bin/env bash

# Originaly from: https://www.reddit.com/r/NixOS/comments/5yxt45/simple_nix_package_search/

CACHE="$HOME/.cache/nq-cache"

run() {
  if ! ( [ -e $CACHE ] && [ $(stat -c %Y $CACHE) -gt $(( $(date +%s) - 3600*24*7 )) ] ); then
          echo "update cache" 1>&2
          nice nix-env -qa --file "<nixpkgs>" --json > "$CACHE"
  fi
  jq -r 'to_entries | .[] | .key + "|" + .value.meta.description' < "$CACHE" |
    {
       if [ $# -gt 0 ]; then
          # double grep because coloring breaks column's char count
          # $* so that we include spaces (could do .* instead?)
            grep -i "$*" | column -t -s "|" | grep --color=always -i "$*"
       else
            column -t -s "|"
       fi
    }
}

usage() {
    echo -e "nix-venient search <pkg>: search for package in <nixpkg>\n"
    echo -e "Examples:\n"
    echo -e "  $ nix-venient search gcc"
    echo -e "  $ nix-venient search tmux"
}

if [[ $# -ne 1 || $1 = "--help" ]]; then
    usage
    exit 1
else
    run $*
fi
